name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the official GitHub for DEMONITIZD BOT. We noticed that you have created an issue and want to fix it. We will get to your issue as soon as possible'
        pr-message: 'We see you have created a pull request, the developers will get back to you as soon as they can. Thank you for your interest'
